 /** DO NOT MODIFY (except where instructed) */
import { getAllCars } from "../getCars";

const cars: any = {
  "abc-def-001": {
    make: "Ford",
    model: "Focus",
    age: 2019,
    mileage: 45000,
    colour: "Blue",
    description: "Well-maintained family hatchback with full service history.",
    cost: 8500,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-002": {
    make: "Volkswagen",
    model: "Golf",
    age: 2020,
    mileage: 32000,
    colour: "Black",
    description: "Popular compact car in great condition.",
    cost: 14000,
    fuelType: "diesel",
    damage: null,
  },
  "abc-def-003": {
    make: "BMW",
    model: "3 Series",
    age: 2018,
    mileage: 61000,
    colour: "White",
    description: "Sporty saloon with leather interior and sat nav.",
    cost: 16500,
    fuelType: "diesel",
    damage: "Minor scratch on rear bumper.",
  },
  "abc-def-004": {
    make: "Toyota",
    model: "Yaris",
    age: 2021,
    mileage: 18000,
    colour: "Red",
    description: "Low mileage city car, ideal for new drivers.",
    cost: 11000,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-005": {
    make: "Audi",
    model: "A4",
    age: 2017,
    mileage: 74000,
    colour: "Silver",
    description: "Executive saloon with high spec and cruise control.",
    cost: 13500,
    fuelType: "diesel",
    damage: "Small dent on driver side door.",
  },
  "abc-def-006": {
    make: "Vauxhall",
    model: "Corsa",
    age: 2022,
    mileage: 9000,
    colour: "White",
    description: "Nearly new with manufacturer warranty remaining.",
    cost: 12500,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-007": {
    make: "Mercedes-Benz",
    model: "C-Class",
    age: 2016,
    mileage: 89000,
    colour: "Grey",
    description: "Premium saloon with heated seats and parking sensors.",
    cost: 12000,
    fuelType: "diesel",
    damage: "Kerbed front alloy wheel.",
  },
  "abc-def-008": {
    make: "Honda",
    model: "Civic",
    age: 2020,
    mileage: 27000,
    colour: "Blue",
    description: "Reliable and fuel-efficient with a spacious boot.",
    cost: 15000,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-009": {
    make: "Nissan",
    model: "Qashqai",
    age: 2019,
    mileage: 52000,
    colour: "Black",
    description: "Popular SUV crossover with panoramic roof.",
    cost: 13000,
    fuelType: "diesel",
    damage: "Light scuff on front wing.",
  },
  "abc-def-010": {
    make: "Kia",
    model: "Sportage",
    age: 2021,
    mileage: 21000,
    colour: "Green",
    description: "Spacious family SUV with remaining manufacturer warranty.",
    cost: 18000,
    fuelType: "diesel",
    damage: null,
  },
  "abc-def-011": {
    make: "Peugeot",
    model: "208",
    age: 2020,
    mileage: 34000,
    colour: "Orange",
    description: "Stylish supermini with touchscreen infotainment.",
    cost: 10500,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-012": {
    make: "Hyundai",
    model: "Tucson",
    age: 2018,
    mileage: 58000,
    colour: "White",
    description: "Reliable SUV with good boot space and tow bar fitted.",
    cost: 11500,
    fuelType: "diesel",
    damage: "Chip on windscreen, repaired.",
  },
  "abc-def-013": {
    make: "Mazda",
    model: "MX-5",
    age: 2017,
    mileage: 41000,
    colour: "Red",
    description: "Fun two-seater convertible, perfect for summer.",
    cost: 14500,
    fuelType: "petrol",
    damage: "Minor lacquer peel on bonnet.",
  },
  "abc-def-014": {
    make: "Renault",
    model: "Clio",
    age: 2022,
    mileage: 12000,
    colour: "Yellow",
    description: "Low mileage with a clean interior and one previous owner.",
    cost: 11000,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-015": {
    make: "Skoda",
    model: "Octavia",
    age: 2019,
    mileage: 67000,
    colour: "Grey",
    description: "Practical estate with a huge boot and good fuel economy.",
    cost: 10000,
    fuelType: "diesel",
    damage: null,
  },
  "abc-def-016": {
    make: "Seat",
    model: "Leon",
    age: 2020,
    mileage: 29000,
    colour: "Black",
    description: "Sporty hatchback with Apple CarPlay and Android Auto.",
    cost: 13500,
    fuelType: "petrol",
    damage: "Scratch on passenger side mirror.",
  },
  "abc-def-017": {
    make: "Fiat",
    model: "500",
    age: 2021,
    mileage: 15000,
    colour: "White",
    description: "Compact city car with retro styling and low running costs.",
    cost: 9500,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-018": {
    make: "Land Rover",
    model: "Discovery Sport",
    age: 2017,
    mileage: 82000,
    colour: "Green",
    description: "Capable off-roader with seven seats and leather trim.",
    cost: 17500,
    fuelType: "diesel",
    damage: "Stone chips on front bumper.",
  },
  "abc-def-019": {
    make: "Citroen",
    model: "C3",
    age: 2021,
    mileage: 19000,
    colour: "Blue",
    description: "Comfortable small car with a smooth ride and quirky design.",
    cost: 9000,
    fuelType: "petrol",
    damage: null,
  },
  "abc-def-020": {
    make: "Volvo",
    model: "XC40",
    age: 2020,
    mileage: 38000,
    colour: "Silver",
    description: "Premium compact SUV with excellent safety features.",
    cost: 22000,
    fuelType: "diesel",
    damage: "Small scratch on tailgate.",
  },
};

export const DB = {
  getCarById: async (id: string): Promise<any> => {
    await new Promise((resolve) => setTimeout(resolve, 500));
    return cars[id] ?? null;
  },
  getAllCars: async (search: any) => {
    await new Promise((resolve) => setTimeout(resolve, 500));

    // comment this out when creating the getCars function - but put it back in when doing the routing challenge
    if (Math.random() < 0.2) {
      throw new Error("Connection to database failed");
    }

    return getAllCars(cars, search);
  }
}

export default cars;
